### ISSUE TITLE
Example config file

### ISSUE THREAD

**Issue by glacials** [BatedUrGonnaDie/salty_bot#14]
If someone other than you or Bomb wants to work on salty, they basically can't. imo it's too much to ask to try to build a config file out of the errors that happen when you don't have one, and contacting one of you guys for whatever the current config file looks like shouldn't be a prerequisite to fix a bug here or there.

I think it's high time that `config.json` gets copied into a `config.default.json`, gets its values replaced with example content, and gets added to the repository.

**Comment by BatedUrGonnaDie** [comment]
There has been a default copy for a few months now, Bomb recently moved it into json docs though

**Comment by glacials** [comment]
Ah okay my bad, didn't think to look there so I assumed one still didn't exist. Is the purpose of this folder just to contain these default config files?

**Comment by BatedUrGonnaDie** [comment]
I believe so since the main folder was getting pretty cluttered.

**Comment by glacials** [comment]
Okay. It could be helpful if `config.default.json` and `config.json` reside in the same directory, wherever that is. So that on a first run, when there are errors about a missing `config.json`, it's obvious when you look in the missing location that there's a `config.default.json` to be used.

**Comment by BatedUrGonnaDie** [comment]
Actually, seeing as I'm trying to remove all extra files, I most likely will not be redo'ing them and moving them back seeing as they will be going away somewhat soon.
